# ?????? ??????? ???? ?? ???? ?????? ??????????
app.data.dir=/tmp/hotel_data
room.status.change.enabled=true
room.residence.history.max=3
state.file.path=/tmp/hotel_data/hotel.bin.txt

# ?????? localhost ?? db
jdbc.url=jdbc:postgresql://db:5432/hotel
jdbc.user=postgres
jdbc.password=postgres
jdbc.driver=org.postgresql.Driver