app.data.dir=C:\Users\ArtemAndroid\Desktop
room.status.change.enabled=true
room.residence.history.max=3
state.file.path=C:\Users\ArtemAndroid\Desktop\hotel.bin.txt

jdbc.url=jdbc:postgresql://localhost:5432/hotel
jdbc.user=postgres
jdbc.password=postgres
jdbc.driver=org.postgresql.Driver